services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6378:6379"

  go-rest-server:
    container_name: go-rest-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379
    volumes:
      - ./files:/app/files